CREATE TABLE IF NOT EXISTS EMPRESA (
    ID_EMPRESA INTEGER PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    RUC TEXT,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME
);

CREATE TABLE IF NOT EXISTS AREA (
    ID_AREA INTEGER PRIMARY KEY,
    ID_EMPRESA INTEGER,
    NOMBRE TEXT NOT NULL,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME,

    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS NOMINA (
    ID_NOMINA INTEGER PRIMARY KEY,
    NOMBRE TEXT NOT NULL,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME
);

CREATE TABLE IF NOT EXISTS SEDE (
    ID_SEDE INTEGER PRIMARY KEY,
    NOMBRE INTEGER,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME
);

CREATE TABLE IF NOT EXISTS TRABAJADOR (
    ID_TRABAJADOR INTEGER,
    CODIGO_INTERNO TEXT,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    NUMERO_DOCUMENTO TEXT,
    FECHA_NACIMIENTO DATE,
    SEXO TEXT,

    ID_AREA INTEGER,
    ID_NOMINA INTEGER,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME,

    FOREIGN KEY(ID_AREA) REFERENCES AREA(ID_AREA),
    FOREIGN KEY(ID_NOMINA) REFERENCES NOMINA(ID_NOMINA)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    NOMBRE_USUARIO TEXT NOT NULL UNIQUE,
    CONTRASENIA TEXT,

    ID_SEDE INTEGER NOT NULL,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME,

    FOREIGN KEY(ID_SEDE) REFERENCES SEDE(ID_SEDE)
);

CREATE TABLE IF NOT EXISTS ASISTENCIA (
    ID_ASISTENCIA INTEGER PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA_ENTRADA TIME(6) NOT NULL,
    HORA_SALIDA TIME(6),
    COMENTARIO TEXT,

    ID_SEDE INTEGER NOT NULL,
    ID_TRABAJADOR INTEGER NOT NULL,

    ESTADO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    FECHA_MODIFICACION DATETIME,

    FOREIGN KEY(ID_SEDE) REFERENCES SEDE(ID_SEDE),
    FOREIGN KEY(ID_TRABAJADOR) REFERENCES TRABAJADOR(ID_TRABAJADOR)
);

CREATE TABLE IF NOT EXISTS MOVIMIENTO (
    ID_MOVIMIENTO INTEGER PRIMARY KEY,
    ID_ASISTENCIA INTEGER,
    HORA TIME(6),

    FOREIGN KEY(ID_ASISTENCIA) REFERENCES ASISTENCIA(ID_ASISTENCIA)
);